/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The repository information is injected during the CI/CD build process
 * to enable fetching data from the data branch
 */

const DATA_CONFIG = {
    /**
     * GitHub repository owner (username)
     * This will be replaced during GitHub Actions workflow execution
     */
    repoOwner: 'Dracoqhl',

    /**
     * GitHub repository name
     * This will be replaced during GitHub Actions workflow execution
     */
    repoName: 'daily-arXiv-ai-enhanced',

    /**
     * Data branch name
     * Default: 'data'
     */
    dataBranch: 'data',

    /**
     * Detect repository owner/name from GitHub Pages URL.
     * Example: https://username.github.io/repo-name/
     *
     * @returns {{owner: string, repo: string}|null}
     */
    detectFromLocation: function() {
        if (typeof window === 'undefined' || !window.location) {
            return null;
        }

        const host = window.location.hostname || '';
        const pathSegments = (window.location.pathname || '')
            .split('/')
            .filter(Boolean);
        const githubPagesMatch = host.match(/^([^.]+)\.github\.io$/i);

        if (!githubPagesMatch || pathSegments.length === 0) {
            return null;
        }

        return {
            owner: githubPagesMatch[1],
            repo: pathSegments[0]
        };
    },

    /**
     * Check whether a value is still an unreplaced placeholder.
     *
     * @param {string} value
     * @returns {boolean}
     */
    isPlaceholderValue: function(value) {
        return !value || value.includes('PLACEHOLDER_');
    },

    /**
     * Initialize repository owner/name.
     * Priority:
     * 1) CI-injected values
     * 2) Auto-detected from current GitHub Pages URL
     * 3) Fallback to upstream defaults
     */
    init: function() {
        const needsOwner = this.isPlaceholderValue(this.repoOwner);
        const needsRepo = this.isPlaceholderValue(this.repoName);

        if (needsOwner || needsRepo) {
            const detected = this.detectFromLocation();
            if (detected) {
                if (needsOwner) this.repoOwner = detected.owner;
                if (needsRepo) this.repoName = detected.repo;
            }
        }

        if (this.isPlaceholderValue(this.repoOwner)) {
            this.repoOwner = 'dw-dengwei';
        }
        if (this.isPlaceholderValue(this.repoName)) {
            this.repoName = 'daily-arXiv-ai-enhanced';
        }
    },

    /**
     * GitHub REST API URL for current repo
     * @returns {string}
     */
    getRepoApiUrl: function() {
        return `https://api.github.com/repos/${this.repoOwner}/${this.repoName}`;
    },

    /**
     * Get the base URL for raw GitHub content from data branch
     * @returns {string} Base URL for raw GitHub content
     */
    getDataBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/${this.dataBranch}`;
    },

    /**
     * Get the full URL for a data file
     * @param {string} filePath - Relative path to the data file (e.g., 'data/2025-01-01.jsonl')
     * @returns {string} Full URL to the data file
     */
    getDataUrl: function(filePath) {
        return `${this.getDataBaseUrl()}/${filePath}`;
    }
};

DATA_CONFIG.init();
